### ISSUE TITLE
iOS10 support

### ISSUE THREAD

**Issue by samuelthng** [PoomSmart/exKeyboard#2]
Crashes on iOS10

PS. Closed because my phone stupidly sent two issue requests instead of one on a bad mobile network... Sorry.

**Comment by PoomSmart** [comment]
This is an issue.

**Comment by samuelthng** [comment]
Latest release fixed.

Works on lockscreen and secure text fields.

iOS 10.2, iPhone 6, Gboard (Google app not Gboard app).
